const networkPanel=document.querySelector("#network-panel"),networkQr=document.querySelector("#network-qr"),networkQrWrap=document.querySelector(".network-qr-wrap"),networkUrl=document.querySelector("#network-url"),playniteButton=document.querySelector("#playnite-fullscreen"),playniteStatus=document.querySelector("#playnite-status"),playnitePromptTitle=document.querySelector("#playnite-prompt-title"),playnitePromptCopy=document.querySelector("#playnite-prompt-copy");
const isDesktop=window.matchMedia("(min-width: 900px) and (hover: hover) and (pointer: fine)").matches;
const GAME_LIBRARY_PORT=8765;
function isLan192(ip){return /^192\.168\.\d{1,3}\.\d{1,3}$/.test(String(ip||""))}
async function getLocalNetworkUrl(){
  try{const r=await fetch("/api/network",{cache:"no-store"});if(r.ok){const d=await r.json();for(const value of [d.local_ip,d.lan_ip,d.ip,d.host,d.address]){const host=String(value||"").replace(/^https?:\/\//,"").split("/")[0].split(":")[0].trim();if(isLan192(host))return `http://${host}:${GAME_LIBRARY_PORT}`;}}}catch(e){console.debug("Local network IP discovery failed",e)}
  const host=window.location.hostname;
  if(isLan192(host))return `http://${host}:${GAME_LIBRARY_PORT}`;
  return null;
}
async function setupNetworkPanel(){if(!networkPanel)return;networkPanel.hidden=false;const url=await getLocalNetworkUrl();if(networkUrl)networkUrl.textContent=url||"No 192.168.x.x LAN address detected";if(isDesktop){if(networkQrWrap)networkQrWrap.style.display=url?"":"none";if(playnitePromptTitle)playnitePromptTitle.textContent="Use Playnite to launch your games";if(playnitePromptCopy)playnitePromptCopy.textContent=url?"For the best experience on this PC, open Playnite Fullscreen. On your phone, scan the QR code to connect to this PC over your local network.":"A QR code is unavailable because no 192.168.x.x LAN address was detected.";if(networkQr&&url){networkQr.alt=`QR code to open ${url} on your phone`;networkQr.src=`/api/network/qr?text=${encodeURIComponent(url)}&t=${Date.now()}`;networkQr.onerror=()=>{if(networkQrWrap)networkQrWrap.classList.add("qr-error")};networkQr.onload=()=>{if(networkQrWrap)networkQrWrap.classList.remove("qr-error")}}}else{if(networkQrWrap)networkQrWrap.style.display="none";if(playnitePromptTitle)playnitePromptTitle.textContent="Use Playnite for the best experience";if(playnitePromptCopy)playnitePromptCopy.textContent="If this page is open on your PC, use Playnite Fullscreen to browse and launch games. From your phone, use GameDrive as the remote library and launcher.";if(networkUrl)networkUrl.textContent=""}try{const r=await fetch("/api/network",{cache:"no-store"});if(r.ok){const d=await r.json();if(d.playnite_configured===false){playniteButton.disabled=true;playniteStatus.textContent="Set playnite_fullscreen_path in config.json"}}}catch(e){console.debug("Playnite status unavailable",e)}}
if(playniteButton)playniteButton.addEventListener("click",async()=>{playniteButton.disabled=true;playniteStatus.textContent="Opening Playnite…";try{const r=await fetch("/api/playnite/fullscreen",{method:"POST"}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||`HTTP ${r.status}`);playniteStatus.textContent="Playnite Fullscreen started"}catch(e){playniteStatus.textContent=`Unable to open: ${e.message}`}finally{setTimeout(()=>{playniteButton.disabled=false},1200)}});
setupNetworkPanel();
